---
title: "Report Group 2"
author: "Pom"
date: "2024-02-28"
output:
  pdf_document:
    toc: yes
    number_sections: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment=NA,attr.source='.numberLines')

rm(list=ls())
library(readr)
library(RSQLite)
library(dplyr)
library(ggplot2)
```

# Task 1.2: SQL Database Schema Creation
```{r connect}
# set up the connection
my_db <- RSQLite::dbConnect(RSQLite::SQLite(),"../database/ecommerse.db")
```

## CREATE tables 
````{bash, eval=FALSE}
# link to SQL file
sqlite3 "../database/ecommerse.db" < "../main/ecommerse_v2.sql"
```

# For Initial load
## Validation and Load files in an sqlite database
```{r}
# Get only Initial file
all_files <- setdiff(list.files("../data_upload/"), list.files("../data_upload/", pattern = "_"))

for (variable in all_files) {
  this_filepath <- paste0("../data_upload/",variable)
  this_file_contents <- readr::read_csv(this_filepath)

  table_name <- gsub(".csv","",variable)
  # Get the primary key column names from the database
  query <- paste("SELECT name FROM pragma_table_info('",table_name,"') WHERE pk = 1;",sep="")
  primary_key_columns <- dbGetQuery(my_db, query)
  
  # Perform Validation
  #source("Validation.R")
  
  RSQLite::dbWriteTable(my_db,table_name,this_file_contents,append=TRUE)
}

```

```{sql connection=my_db}

select *
from customers;
```


# Data Analysis using SQL 

```{sql connection=my_db}
SELECT * 
FROM customers
LIMIT 10;
```
```{sql connection=my_db}
-- Products
SELECT * 
FROM products
LIMIT 10;
```


```{sql connection=my_db}
-- Number of Categories
SELECT COUNT(*) AS total_categories
FROM categories;
```

```{sql connection=my_db}
-- Maximum Number of Orders placed by any customer
SELECT MAX(total_orders) AS max_orders
FROM (SELECT COUNT(id) AS total_orders
      FROM orders
      GROUP BY customer_id) AS order_counts;

```


```{sql connection=my_db}
-- Top 5 sellers by the revenue generated
SELECT s.name AS seller_name, SUM(p.price * o.quantity * (1 - (o.discount / 100))) AS total_revenue
FROM sellers AS s
INNER JOIN products AS p ON s.id = p.seller_id
INNER JOIN orders AS o ON p.id = o.product_id
GROUP BY s.name
ORDER BY total_revenue DESC
LIMIT 5;


```


```{sql connection=my_db}
-- Top 10 best-selling products by the quantity sold 
SELECT p.name AS product_name, SUM(o.quantity) AS total_sold
FROM products AS p
INNER JOIN orders AS o ON p.id = o.product_id
GROUP BY p.name
ORDER BY total_sold DESC
LIMIT 10;


```

```{sql connection=my_db}
-- Top 10 customers by the total amount spent
SELECT c.id AS customer_id, CONCAT(c.first_name, ' ', c.last_name) AS customer_name, 
       SUM(p.price * o.quantity * (1 - o.discount)) AS total_spent
FROM customers AS c
INNER JOIN orders AS o ON c.id = o.customer_id
INNER JOIN products AS p ON o.product_id = p.id
GROUP BY c.id, customer_name
ORDER BY total_spent DESC
LIMIT 10;


```


```{sql connection=my_db}
-- Top 10 shippers with highest number of shippings
SELECT s.name AS shipper_name, COUNT(*) AS total_shippings
FROM shippers AS s
JOIN orders AS o ON s.id = o.shipper_id
GROUP BY s.name
ORDER BY total_shippings DESC
LIMIT 10;

```

```{sql connection=my_db}
-- Average discount percentage applied to orders
SELECT AVG(discount) AS average_discount
FROM orders;
```


```{r}
## Categories with number of products in each category

category_products <- dbGetQuery(my_db, "SELECT c.name AS category_name, COUNT(p.id) AS num_products
                              FROM products AS p
                              INNER JOIN categories AS c ON p.category_id = c.id
                              GROUP BY p.category_id, c.name
                              ORDER BY num_products DESC
                              LIMIT 10")

ggplot(category_products, aes(x = reorder(category_name, -num_products), y = num_products)) +
  geom_bar(stat = "identity", fill = "maroon", color = "black") +
  labs(title = "Number of Products in Each Category",
       x = "Category Name",
       y = "Number of Products") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        axis.title.y = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        plot.title = element_text(size = 14, hjust = 0.5),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        plot.margin = margin(t = 0.5, r = 0.5, b = 1, l = 1, unit = "cm")) +  # Specify margins
  geom_text(aes(label = num_products), vjust = -0.3, size = 3, color = "black")  # Add labels for each bar

```
# Reading data from database after validation

```{r}

# Define SQL queries for each table
sql_queries <- list(
  orders = "SELECT * FROM orders",
  customers = "SELECT * FROM customers",
  categories = "SELECT * FROM categories",
  advertisements = "SELECT * FROM advertisements",
  shippers = "SELECT * FROM shippers",
  products = "SELECT * FROM products",
  sellers = "SELECT * FROM sellers"
)


# Read data from each table using SQL queries

orders <- dbGetQuery(my_db, 
                     sql_queries$orders)
customers <- dbGetQuery(my_db, 
                        sql_queries$customers)
categories <- dbGetQuery(my_db, 
                         sql_queries$categories)
advertisements <- dbGetQuery(my_db, 
                             sql_queries$advertisements)
shippers <- dbGetQuery(my_db, 
                       sql_queries$shippers)
products <- dbGetQuery(my_db, 
                       sql_queries$products)
sellers <- dbGetQuery(my_db, 
                      sql_queries$sellers)

```

# Using dplyr, tidyr and ggplot to visualise the data

```{r}
# Top 10 Customers segmented by the Total Amount Spent
order_details <- orders %>%
  inner_join(products, by = "id") %>%
  inner_join(customers, by = "id")

# Calculate total amount spent by each customer
customer_spending <- order_details %>%
  group_by(customer_id, first_name, last_name) %>%
  summarise(total_spent = sum(price * quantity * (1 - (discount / 100))), .groups = "drop") %>%
  arrange(desc(total_spent)) %>%
  top_n(10, total_spent)

# Plot top 10 customers with respect to amount spent
ggplot(customer_spending, aes(x = reorder(paste(first_name, last_name), -total_spent), y = total_spent)) +
  geom_bar(stat = "identity", fill = "salmon") +  # Change fill color to salmon
  labs(title = "Top 10 Customers by Amount Spent",
       x = "Customer",
       y = "Total Amount Spent") +
  coord_flip() +  # Flip the axis
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, color = "black")) 
```


```{r}
# Top 10 selling products
product_sales <- order_details %>%
  group_by(product_id, name) %>%
  summarise(total_quantity_sold = sum(quantity)) %>%
  arrange(desc(total_quantity_sold)) %>%
  top_n(10, total_quantity_sold)

top_10_products <- head(product_sales, 10)

ggplot(top_10_products, aes(x = reorder(name, total_quantity_sold), y = total_quantity_sold)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Top 10 Selling Products",
       x = "Product",
       y = "Total Quantity Sold") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}
# Top 10 shippers by the number of orders shipped
shipper_counts <- orders %>%
  group_by(shipper_id) %>%
  summarise(total_orders = n()) %>%
  arrange(desc(total_orders)) %>%
  slice(1:10)  

ggplot(shipper_counts, aes(x = reorder(shipper_id, total_orders), y = total_orders)) +
  geom_bar(stat = "identity", fill = "grey") +
  labs(title = "Orders by Shipper",
       x = "Shipper ID",
       y = "Total Orders") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```



```{r}
# check the strcture of the dataset
str(product_data)
```

```{r}
summary(product_data)
```

```{r}
head(product_data)
```

```{r}
# Analysis on product price
ggplot(product_data, aes(x = price)) +
  geom_histogram(binwidth = 10, fill = "blue") +
  labs(title = "Product Price Distribution", x = "Price", y = "Frequency")
```


```{r}
# Analysis the product brand
brand_counts <- product_data %>%
  group_by(brand) %>%
  summarise(count = n()) %>%
  arrange(desc(count))

select_brand <- brand_counts[1:15, ]

ggplot(select_brand, aes(x = reorder(brand, -count), y = count)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  labs(title = "Product Brand Distribution", x = "Brand", y = "Count")
```

```{r}
# create a table to calculate the sales data
product_sales <- order_data %>%
  group_by(product_id) %>%
  summarise(total_quantity = sum(quantity)) %>%
  inner_join(product_data %>%
              group_by(product_id) %>%
              summarise(single_price = price), 
            by = "product_id")

product_sales$total_revenue <- product_sales$total_quantity * product_sales$single_price

# Sort by sales quantity and revenue, find the product with the highest sales quantity
best_selling_products_by_quantity <- product_sales %>%
  arrange(desc(total_quantity)) %>%
  head(10) 

best_selling_products_by_revenue <- product_sales %>%
  arrange(desc(total_revenue)) %>%
  head(10)  
```


```{r}
# highest sales quantity
ggplot(best_selling_products_by_quantity, aes(x = reorder(product_id, -total_quantity), y = total_quantity)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(title = "Top 10 Best-Selling Products by Quantity", x = "Product ID", y = "Total Quantity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

# highest sales revenue
ggplot(best_selling_products_by_revenue, aes(x = reorder(product_id, -total_revenue), y = total_revenue)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(title = "Top 10 Best-Selling Products by Revenue", x = "Product ID", y = "Total Revenue") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

# Analysis on how price affect sales quantity
ggplot(product_sales, aes(x = single_price, y = total_quantity)) +
  geom_point(color = "blue") +
  labs(title = "Price vs. Sales Quantity",
       x = "Price",
       y = "Total Quantity Sold")

```


```{r}
# merge product_data and ads_data to get each product's ads clicks
product_ads <- left_join(product_data, advertisement_data, by = "product_id")

# calculate each product's total ads clicks
ads_clicks_data <- product_ads %>%
  group_by(product_id, name) %>%
  summarise(total_clicks = sum(ads_clicks, na.rm = TRUE))

ggplot(ads_clicks_data, aes(x = name, y = total_clicks)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(title = "Product vs. Ads Clicks", x = "Product Name", y = "Total Ads Clicks") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

```{r}
product_review <- left_join(product_data, order_data, by = "product_id")

# calculate each product's average rating
product_rating_data <- product_review %>%
  group_by(product_id, name) %>%
  summarise(avg_rating = mean(rating_review, na.rm = TRUE))

# plot relationship between product and rating
ggplot(product_rating_data, aes(x = name, y = avg_rating)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(title = "Product vs. Average Rating", x = "Product Name", y = "Average Rating") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


Close Connection
```{r disconnect}
# Disconnect from the database using the connection variable that we setup 
# before
RSQLite::dbDisconnect(my_db)

```





